##
stages:
  - build
  - sonar
  - test

build:
  stage: build
  script: ./gradlew assemble

sonar:
  stage: sonar
  script: ./gradlew -D sonar.projectKey=staticCodeAnysis -D sonar.host.url=http://localhost:9000 -D sonar.login=3a75aaa485111e6b80e037bf77e8e6be8df02382
test:
  stage: test
  script: ./gradlew test


after_script:
  - echo "End CI~!"
