##
stages:
  - build
  - sonar
  - test

build:
  stage: build
  script: ./gradlew assemble

sonar:
  stage: sonar
  script: ./gradlew sonarqube Dsonar.projectKey=getandgo Dsonar.host.url=http://localhost:9000 Dsonar.login=c586cc2062044e3a94b188daf32852ddf1a128fe

test:
  stage: test
  script: ./gradlew test


after_script:
  - echo "End CI~!"