##
stages:
  - build
  - sonar
  - test

build:
  stage: build
  script: ./gradlew assemble

sonar:
  stage: sonar
  script: ./gradlew Dsonar.projectKey=staticCodeAnysis Dsonar.host.url=http://localhost:9000 Dsonar.login=b130d4ee9025896e5c087ace7c41eb5e86e3ebd1
test:
  stage: test
  script: ./gradlew test


after_script:
  - echo "End CI~!"
