##
stages:
  - remove_local_cache_file
  - build
  - sonar
  - test

remove_local_cache_file:
  stage: remove_local_cache_file
  script:rm -rf builds 
  

build:
  stage: build
  script: ./gradlew assemble

sonar:
  stage: sonar
  script: ./gradlew sonarqube -D sonar.projectKey=getandgo -D sonar.host.url=%URL% -D sonar.login=%SONARKEY%
test:
  stage: test
  script: ./gradlew test


after_script:
  - echo "End CI~!"