stages:
  - build
  - sonar
  - test
  - deploy-docker
build:
  stage: build
  script: ./gradlew assemble

sonar:
  stage: sonar
  script: ./gradlew jacocoTestReport sonarqube -D sonar.projectKey=getandgo -D sonar.host.url=%URL% -D sonar.login=%SONARKEY%
test:
  stage: test
  script: ./gradlew test

deploy-docker:
  image: docker:latest
  stage: deploy-docker
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PSW"
  script:
    - docker build . -f Dockerfile -t "$DOCKER_REGISTRY_IMAGE"
    - docker push "$DOCKER_REGISTRY_IMAGE"
after_script:
  - echo "End CI~!"